let ALL_STATIONS = [
    ["Kanda", "神田", "Kanda", 0, 0, ["東京メトロ銀座線", "JR山手線", "JR京浜東北線", "JR中央線",]],
    ["Mitsukoshimae", "三越前", "Mitsukoshimae", 0, 0, ["東京メトロ銀座線", "東京メトロ半蔵門線",]],
    ["Shinnihonbashi", "新日本橋", "Shinnihonbashi", 0, 0, ["JR総武本線",]],
    ["Kanda", "秋葉原", "Akihabara", 5, 0, ["東京メトロ日比谷線", "JR山手線", "JR京浜東北線", "JR総武線",]],
    ["Kanda", "東京", "Tokyo", 5, 0, ["東京メトロ丸ノ内線", "JR山手線", "JR京浜東北線", "JR中央線", "JR東海道本線", "JR横須賀線", "JR京葉線", "JR中央本線(東京～塩尻)", "JR総武本線",]],
    ["Mitsukoshimae", "日本橋", "Nipponbashi", 6, 0, ["東京メトロ銀座線", "東京メトロ東西線", "都営地下鉄浅草線",]],
    ["Kanda", "御徒町", "Okachimachi", 7, 0, ["JR山手線", "JR京浜東北線",]],
    ["Mitsukoshimae", "末広町", "Suehirocho", 7, 0, ["東京メトロ銀座線",]],
    ["Kanda", "有楽町", "Yurakucho", 7, 0, ["東京メトロ有楽町線", "JR山手線", "JR京浜東北線",]],
    ["Mitsukoshimae", "京橋", "Kyobashi", 8, 0, ["東京メトロ銀座線",]],
    ["Kanda", "御茶ノ水", "Ochanomizu", 8, 0, ["東京メトロ丸ノ内線", "JR中央線", "JR総武線",]],
    ["Mitsukoshimae", "水天宮前", "Suitengumae", 8, 0, ["東京メトロ半蔵門線",]],
    ["Kanda", "上野広小路", "Ueno Hirokoji", 8, 0, ["東京メトロ銀座線",]],
    ["Kanda", "上野", "Ueno", 9, 0, ["東京メトロ日比谷線", "東京メトロ銀座線", "JR山手線", "JR京浜東北線", "JR常磐線(上野～取手)",]],
    ["Shinnihonbashi", "馬喰町", "Bakurocho", 10, 0, ["JR総武本線",]],
    ["Mitsukoshimae", "銀座", "Ginza", 10, 0, ["東京メトロ日比谷線", "東京メトロ銀座線", "東京メトロ丸ノ内線",]],
    ["Mitsukoshimae", "大手町", "Otemachi", 10, 0, ["東京メトロ千代田線", "東京メトロ丸ノ内線", "東京メトロ半蔵門線", "東京メトロ東西線", "都営地下鉄三田線",]],
    ["Kanda", "新橋", "Shimbashi", 10, 0, ["東京メトロ銀座線", "都営地下鉄浅草線", "JR山手線", "JR京浜東北線", "JR東海道本線", "JR横須賀線", "ゆりかもめ",]],
    ["Kanda", "浜松町", "Hamamatsucho", 11, 0, ["JR山手線", "JR京浜東北線", "東京モノレール",]],
    ["Kanda", "岩本町", "Iwamotocho", 11, 0, ["都営地下鉄新宿線",]],
    ["Mitsukoshimae", "神保町", "Jimbocho", 11, 0, ["東京メトロ半蔵門線", "都営地下鉄三田線", "都営地下鉄新宿線",]],
    ["Mitsukoshimae", "清澄白河", "Kiyosumi Shirakawa", 11, 0, ["東京メトロ半蔵門線", "都営地下鉄大江戸線",]],
    ["Kanda", "仲御徒町", "Nakaokachimachi", 11, 0, ["東京メトロ日比谷線",]],
    ["Mitsukoshimae", "上野御徒町", "Ueno Okachimachi", 11, 0, ["都営地下鉄大江戸線",]],
    ["Shinnihonbashi", "馬喰横山", "Bakuroyokoyama", 12, 0, ["都営地下鉄新宿線",]],
    ["Kanda", "日比谷", "Hibiya", 12, 0, ["東京メトロ日比谷線", "東京メトロ千代田線", "都営地下鉄三田線",]],
    ["Mitsukoshimae", "九段下", "Kudanshita", 12, 0, ["東京メトロ半蔵門線", "東京メトロ東西線", "都営地下鉄新宿線",]],
    ["Kanda", "浅草橋", "Asakusabashi", 12, 1, ["都営地下鉄浅草線", "JR総武線",]],
    ["Kanda", "水道橋", "Suidobashi", 12, 1, ["都営地下鉄三田線", "JR中央線", "JR総武線",]],
    ["Kanda", "日暮里", "Nippori", 13, 0, ["日暮里・舎人ライナー", "JR山手線", "JR京浜東北線", "JR常磐線(上野～取手)", "京成本線",]],
    ["Kanda", "田町", "Tamachi", 13, 0, ["JR山手線", "JR京浜東北線",]],
    ["Mitsukoshimae", "虎ノ門", "Toranomon", 13, 0, ["東京メトロ銀座線",]],
    ["Kanda", "四ツ谷", "Yotsuya", 13, 0, ["東京メトロ南北線", "東京メトロ丸ノ内線", "JR中央線", "JR総武線", "JR中央本線(東京～塩尻)",]],
    ["Mitsukoshimae", "茅場町", "Kayabacho", 13, 1, ["東京メトロ日比谷線", "東京メトロ東西線",]],
    ["Mitsukoshimae", "宝町", "Takaracho", 13, 1, ["都営地下鉄浅草線",]],
    ["Kanda", "京成上野", "Keisei Ueno", 14, 0, ["京成本線",]],
    ["Shinnihonbashi", "錦糸町", "Kinshicho", 14, 0, ["東京メトロ半蔵門線", "JR総武線", "JR総武本線",]],
    ["Mitsukoshimae", "人形町", "Ningyocho", 14, 0, ["東京メトロ日比谷線", "都営地下鉄浅草線",]],
    ["Kanda", "西日暮里", "Nishinippori", 14, 0, ["東京メトロ千代田線", "日暮里・舎人ライナー", "JR山手線", "JR京浜東北線",]],
    ["Kanda", "新御茶ノ水", "Shin-Ochanomizu", 14, 0, ["東京メトロ千代田線",]],
    ["Mitsukoshimae", "住吉", "Sumiyoshi", 14, 0, ["東京メトロ半蔵門線", "都営地下鉄新宿線",]],
    ["Mitsukoshimae", "東銀座", "Higashiginza", 14, 1, ["東京メトロ日比谷線", "都営地下鉄浅草線",]],
    ["Kanda", "飯田橋", "Iidabashi", 14, 1, ["東京メトロ南北線", "東京メトロ有楽町線", "東京メトロ東西線", "都営地下鉄大江戸線", "JR中央線", "JR総武線",]],
    ["Kanda", "両国", "Ryogoku", 14, 1, ["都営地下鉄大江戸線", "JR総武線",]],
    ["Kanda", "銀座一丁目", "Ginza-itchome", 15, 0, ["東京メトロ有楽町線",]],
    ["Mitsukoshimae", "半蔵門", "Hanzomon", 15, 0, ["東京メトロ半蔵門線",]],
    ["Shinnihonbashi", "東日本橋", "Higashi-nihonbashi", 15, 0, ["都営地下鉄浅草線",]],
    ["Kanda", "田端", "Tabata", 15, 0, ["JR山手線", "JR京浜東北線",]],
    ["Kanda", "高輪ゲートウェイ", "Takanawa Gateway", 15, 0, ["JR山手線",]],
    ["Kanda", "淡路町", "Awajicho", 15, 1, ["東京メトロ丸ノ内線",]],
    ["Kanda", "本郷三丁目", "Hongo Sanchome", 15, 1, ["東京メトロ丸ノ内線", "都営地下鉄大江戸線",]],
    ["Mitsukoshimae", "門前仲町", "Monzennakacho", 15, 1, ["東京メトロ東西線", "都営地下鉄大江戸線",]],
    ["Kanda", "市ヶ谷", "Ichigaya", 16, 1, ["東京メトロ南北線", "東京メトロ有楽町線", "都営地下鉄新宿線", "JR中央線", "JR総武線",]],
    ["Kanda", "小伝馬町", "Kodenmacho", 16, 1, ["東京メトロ日比谷線",]],
    ["Kanda", "新富町", "Shintomicho", 16, 1, ["東京メトロ有楽町線",]],
    ["Mitsukoshimae", "竹橋", "Takebashi", 16, 1, ["東京メトロ東西線",]],
    ["Mitsukoshimae", "赤坂見附", "Akasakamitsuke", 17, 0, ["東京メトロ銀座線", "東京メトロ丸ノ内線",]],
    ["Mitsukoshimae", "永田町", "Nagatacho", 17, 0, ["東京メトロ南北線", "東京メトロ半蔵門線", "東京メトロ有楽町線",]],
    ["Kanda", "内幸町", "Uchisaiwaicho", 17, 0, ["都営地下鉄三田線",]],
    ["Mitsukoshimae", "木場", "Kiba", 17, 1, ["東京メトロ東西線",]],
    ["Kanda", "後楽園", "Korakuen", 17, 1, ["東京メトロ丸ノ内線",]],
    ["Kanda", "大門", "Daimon", 18, 0, ["都営地下鉄大江戸線", "都営地下鉄浅草線",]],
    ["Kanda", "駒込", "Komagome", 18, 0, ["東京メトロ南北線", "JR山手線",]],
    ["Kanda", "小川町", "Ogawamachi", 18, 0, ["都営地下鉄新宿線",]],
    ["Mitsukoshimae", "押上〈スカイツリー前〉", "Oshiage", 18, 0, ["東京メトロ半蔵門線", "都営地下鉄浅草線", "東武伊勢崎線",]],
    ["Kanda", "品川", "Shinagawa", 18, 0, ["JR山手線", "JR京浜東北線", "JR東海道本線", "JR横須賀線", "京急本線",]],
    ["Kanda", "新宿", "Shinjuku", 18, 0, ["東京メトロ丸ノ内線", "都営地下鉄大江戸線", "都営地下鉄新宿線", "JR山手線", "JR埼京線", "JR中央線", "JR総武線", "JR中央本線(東京～塩尻)", "小田急電鉄小田原線", "京王線",]],
    ["Mitsukoshimae", "溜池山王", "Tameike Sanno", 18, 0, ["東京メトロ南北線", "東京メトロ銀座線",]],
    ["Kanda", "亀戸", "Kameido", 18, 1, ["JR総武線", "東武亀戸線",]],
    ["Mitsukoshimae", "霞ヶ関", "Kasumigaseki", 18, 1, ["東京メトロ日比谷線", "東京メトロ千代田線", "東京メトロ丸ノ内線",]],
    ["Kanda", "麹町", "Kojimachi", 18, 1, ["東京メトロ有楽町線",]],
    ["Mitsukoshimae", "蔵前", "Kuramae", 18, 1, ["都営地下鉄大江戸線", "都営地下鉄浅草線",]],
    ["Mitsukoshimae", "森下", "Morishita", 18, 1, ["都営地下鉄大江戸線", "都営地下鉄新宿線",]],
    ["Kanda", "汐留", "Shiodome", 18, 1, ["都営地下鉄大江戸線", "ゆりかもめ",]],
    ["Kanda", "月島", "Tsukishima", 18, 1, ["東京メトロ有楽町線", "都営地下鉄大江戸線",]],
    ["Kanda", "春日", "Kasuga", 19, 1, ["都営地下鉄大江戸線", "都営地下鉄三田線",]],
    ["Kanda", "茗荷谷", "Myogadani", 19, 1, ["東京メトロ丸ノ内線",]],
    ["Mitsukoshimae", "東陽町", "Toyocho", 19, 1, ["東京メトロ東西線",]],
    ["Mitsukoshimae", "青山一丁目", "Aoyama-itchome", 20, 0, ["東京メトロ銀座線", "東京メトロ半蔵門線", "都営地下鉄大江戸線",]],
    ["Kanda", "三田", "Mita", 20, 0, ["都営地下鉄三田線", "都営地下鉄浅草線",]],
    ["Kanda", "大崎", "Osaki", 20, 0, ["JR山手線", "JR埼京線", "りんかい線",]],
    ["Kanda", "巣鴨", "Sugamo", 20, 0, ["都営地下鉄三田線", "JR山手線",]],
    ["Mitsukoshimae", "虎ノ門ヒルズ", "Toranomon Hills", 20, 0, ["東京メトロ日比谷線",]],
    ["Mitsukoshimae", "八丁堀", "Hatchobori", 20, 1, ["東京メトロ日比谷線", "JR京葉線",]],
    ["Kanda", "平井", "Hirai", 20, 1, ["JR総武線",]],
    ["Mitsukoshimae", "六本木一丁目", "Roppongi Itchome", 20, 1, ["東京メトロ南北線",]],
    ["Kanda", "信濃町", "Shinanomachi", 20, 1, ["JR中央線", "JR総武線",]],
    ["Kanda", "豊洲", "Toyosu", 20, 1, ["東京メトロ有楽町線", "ゆりかもめ",]],
    ["Mitsukoshimae", "築地", "Tsukiji", 20, 1, ["東京メトロ日比谷線",]],
    ["Kanda", "四谷三丁目", "Yotsuya Sanchome", 20, 1, ["東京メトロ丸ノ内線",]],
    ["Mitsukoshimae", "湯島", "Yushima", 20, 1, ["東京メトロ千代田線",]],
    ["Mitsukoshimae", "外苑前", "Gaienmae", 21, 0, ["東京メトロ銀座線",]],
    ["Mitsukoshimae", "表参道", "Omotesando", 21, 0, ["東京メトロ千代田線", "東京メトロ銀座線", "東京メトロ半蔵門線",]],
    ["Kanda", "白山", "Hakusan", 21, 1, ["都営地下鉄三田線",]],
    ["Mitsukoshimae", "本所吾妻橋", "Honjoazumabashi", 21, 1, ["都営地下鉄浅草線",]],
    ["Mitsukoshimae", "南砂町", "Minamisunamachi", 21, 1, ["東京メトロ東西線",]],
    ["Kanda", "御成門", "Onarimon", 21, 1, ["都営地下鉄三田線",]],
    ["Kanda", "新大塚", "Shin Otsuka", 21, 1, ["東京メトロ丸ノ内線",]],
    ["Kanda", "竹芝", "Takeshiba", 21, 1, ["ゆりかもめ",]],
    ["Kanda", "牛込神楽坂", "Ushigome Kagurazaka", 21, 1, ["都営地下鉄大江戸線",]],
    ["Kanda", "五反田", "Gotanda", 22, 0, ["都営地下鉄浅草線", "JR山手線", "東京急行電鉄東急池上線",]],
    ["Kanda", "国会議事堂前", "Kokkaigijidomae", 22, 0, ["東京メトロ千代田線", "東京メトロ丸ノ内線",]],
    ["Kanda", "中野", "Nakano", 22, 0, ["東京メトロ東西線", "JR中央線", "JR総武線",]],
    ["Kanda", "大塚", "Otsuka", 22, 0, ["JR山手線",]],
    ["Kanda", "泉岳寺", "Sengakuji", 22, 0, ["都営地下鉄浅草線", "京急本線",]],
    ["Mitsukoshimae", "麻布十番", "Azabu Juban", 22, 1, ["東京メトロ南北線", "都営地下鉄大江戸線",]],
    ["Shinnihonbashi", "浜町", "Hamacho", 22, 1, ["都営地下鉄新宿線",]],
    ["Kanda", "日の出", "Hinode", 22, 1, ["ゆりかもめ",]],
    ["Mitsukoshimae", "勝どき", "Kachidoki", 22, 1, ["都営地下鉄大江戸線",]],
    ["Mitsukoshimae", "神楽坂", "Kagurazaka", 22, 1, ["東京メトロ東西線",]],
    ["Mitsukoshimae", "根津", "Nezu", 22, 1, ["東京メトロ千代田線",]],
    ["Kanda", "千駄ヶ谷", "Sendagaya", 22, 1, ["JR中央線", "JR総武線",]],
    ["Kanda", "千駄木", "Sendagi", 22, 1, ["東京メトロ千代田線",]],
    ["Kanda", "新宿御苑前", "Shinjuku Gyoenmae", 22, 1, ["東京メトロ丸ノ内線",]],
    ["Kanda", "新宿西口", "Shinjuku Nishiguchi", 23, 0, ["都営地下鉄大江戸線",]],
    ["Kanda", "江戸川橋", "Edogawabashi", 23, 1, ["東京メトロ有楽町線",]],
    ["Kanda", "越中島", "Etchujima", 23, 1, ["JR京葉線",]],
    ["Mitsukoshimae", "神谷町", "Kamiyacho", 23, 1, ["東京メトロ日比谷線",]],
    ["Kanda", "千石", "Sengoku", 23, 1, ["都営地下鉄三田線",]],
    ["Kanda", "芝公園", "Shibakoen", 23, 1, ["都営地下鉄三田線",]],
    ["Kanda", "新宿三丁目", "Shinjuku Sanchome", 23, 1, ["東京メトロ丸ノ内線", "東京メトロ副都心線", "都営地下鉄新宿線",]],
    ["Kanda", "新大久保", "Shinokubo", 23, 1, ["JR山手線",]],
    ["Kanda", "辰巳", "Tatsumi", 23, 1, ["東京メトロ有楽町線",]],
    ["Kanda", "牛込柳町", "Ushigome Yanagicho", 23, 1, ["都営地下鉄大江戸線",]],
    ["Kanda", "代々木", "Yoyogi", 23, 1, ["都営地下鉄大江戸線", "JR山手線", "JR中央線", "JR総武線",]],
    ["Kanda", "高円寺", "Koenji", 24, 0, ["JR中央線", "JR総武線",]],
    ["Kanda", "目黒", "Meguro", 24, 0, ["東京メトロ南北線", "都営地下鉄三田線", "JR山手線", "東京急行電鉄東急目黒線",]],
    ["Shinnihonbashi", "西大井", "Nishioi", 24, 0, ["JR横須賀線",]],
    ["Mitsukoshimae", "渋谷", "Shibuya", 24, 0, ["東京メトロ銀座線", "東京メトロ半蔵門線", "東京メトロ副都心線", "JR山手線", "JR埼京線", "東京急行電鉄東急東横線", "東京急行電鉄東急田園都市線", "京王井の頭線",]],
    ["Mitsukoshimae", "曙橋", "Akebonobashi", 24, 1, ["都営地下鉄新宿線",]],
    ["Mitsukoshimae", "菊川", "Kikugawa", 24, 1, ["都営地下鉄新宿線",]],
    ["Mitsukoshimae", "西大島", "Nishi Oshima", 24, 1, ["都営地下鉄新宿線",]],
    ["Kanda", "芝浦ふ頭", "Shibaurafuto", 24, 1, ["ゆりかもめ",]],
    ["Mitsukoshimae", "白金高輪", "Shirokane Takanawa", 24, 1, ["東京メトロ南北線", "都営地下鉄三田線",]],
    ["Mitsukoshimae", "高輪台", "Takanawadai", 24, 1, ["都営地下鉄浅草線",]],
    ["Mitsukoshimae", "早稲田", "Waseda", 24, 1, ["東京メトロ東西線", "都電荒川線",]],
    ["Kanda", "池袋", "Ikebukuro", 25, 0, ["東京メトロ丸ノ内線", "東京メトロ有楽町線", "東京メトロ副都心線", "JR山手線", "JR埼京線", "東武東上線", "西武池袋線",]],
    ["Kanda", "高田馬場", "Takadanobaba", 25, 0, ["東京メトロ東西線", "JR山手線", "西武新宿線",]],
    ["Kanda", "赤羽橋", "Akabanebashi", 25, 1, ["都営地下鉄大江戸線",]],
    ["Mitsukoshimae", "赤坂", "Akasaka", 25, 1, ["東京メトロ千代田線",]],
    ["Kanda", "原宿", "Harajuku", 25, 1, ["JR山手線",]],
    ["Kanda", "大久保", "Okubo", 25, 1, ["JR中央線", "JR総武線",]],
    ["Mitsukoshimae", "大島", "Oshima", 25, 1, ["都営地下鉄新宿線",]],
    ["Kanda", "新木場", "Shinkiba", 25, 1, ["東京メトロ有楽町線", "JR京葉線", "りんかい線",]],
    ["Kanda", "東大前", "Todaimae", 25, 1, ["東京メトロ南北線",]],
    ["Mitsukoshimae", "築地市場", "Tsukiji Market", 25, 1, ["都営地下鉄大江戸線",]],
    ["Kanda", "若松河田", "Wakamatsukawada", 25, 1, ["都営地下鉄大江戸線",]],
    ["Kanda", "赤羽", "Akabane", 26, 0, ["JR京浜東北線", "JR埼京線",]],
    ["Kanda", "阿佐ヶ谷", "Asagaya", 26, 0, ["JR中央線", "JR総武線",]],
    ["Kanda", "護国寺", "Gokokuji", 26, 1, ["東京メトロ有楽町線",]],
    ["Kanda", "本駒込", "Honkomagome", 26, 1, ["東京メトロ南北線",]],
    ["Kanda", "南新宿", "Minami-Shinjuku", 26, 1, ["小田急電鉄小田原線",]],
    ["Kanda", "国立競技場", "National stadium", 26, 1, ["都営地下鉄大江戸線",]],
    ["Kanda", "乃木坂", "Nogizaka", 26, 1, ["東京メトロ千代田線",]],
    ["Kanda", "六本木", "Roppongi", 26, 1, ["東京メトロ日比谷線", "都営地下鉄大江戸線",]],
    ["Kanda", "潮見", "Shiomi", 26, 1, ["JR京葉線",]],
    ["Mitsukoshimae", "白金台", "Shirokanedai", 26, 1, ["東京メトロ南北線", "都営地下鉄三田線",]],
    ["Kanda", "亀戸水神", "Kameidosuijin", 26, 2, ["東武亀戸線",]],
    ["Kanda", "品川シーサイド", "Shinagawa Seaside", 26, 2, ["りんかい線",]],
    ["Kanda", "恵比寿", "Ebisu", 27, 0, ["東京メトロ日比谷線", "JR山手線", "JR埼京線",]],
    ["Kanda", "蒲田", "Kamata", 27, 0, ["東京急行電鉄東急池上線", "東急多摩川線",]],
    ["Kanda", "目白", "Mejiro", 27, 0, ["JR山手線",]],
    ["Kanda", "西武新宿", "Seibu Shinjuku", 27, 0, ["西武新宿線",]],
    ["Kanda", "東中野", "Higashi Nakano", 27, 1, ["都営地下鉄大江戸線", "JR中央線", "JR総武線",]],
    ["Mitsukoshimae", "東大島", "Higashi Ojima", 27, 1, ["都営地下鉄新宿線",]],
    ["Kanda", "東新宿", "Higashi-Shinjuku", 27, 1, ["東京メトロ副都心線", "都営地下鉄大江戸線",]],
    ["Kanda", "熊野前", "Kumanomae", 27, 1, ["都電荒川線", "日暮里・舎人ライナー",]],
    ["Kanda", "明治神宮前〈原宿〉", "Meijijingumae", 27, 1, ["東京メトロ千代田線", "東京メトロ副都心線",]],
    ["Kanda", "西新宿", "Nishi-Shinjuku", 27, 1, ["東京メトロ丸ノ内線",]],
    ["Kanda", "参宮橋", "Sangubashi", 27, 1, ["小田急電鉄小田原線",]],
    ["Kanda", "荻窪", "Ogikubo", 28, 0, ["東京メトロ丸ノ内線", "JR中央線", "JR総武線",]],
    ["Kanda", "東池袋", "Higashi-Ikebukuro", 28, 1, ["東京メトロ有楽町線",]],
    ["Kanda", "北品川", "Kitashinagawa", 28, 1, ["京急本線",]],
    ["Kanda", "大崎広小路", "Osaki Hirokoji", 28, 1, ["東京急行電鉄東急池上線",]],
    ["Kanda", "下神明", "Shimoshinmei", 28, 1, ["東京急行電鉄東急大井町線",]],
    ["Kanda", "とうきょうスカイツリー", "Tokyo Skytree", 28, 1, ["東武伊勢崎線",]],
    ["Kanda", "新豊洲", "Shin-Toyosu", 28, 2, ["ゆりかもめ",]],
    ["Kanda", "足立小台", "Adachi Odai", 29, 1, ["日暮里・舎人ライナー",]],
    ["Mitsukoshimae", "広尾", "Hiroo", 29, 1, ["東京メトロ日比谷線",]],
    ["Kanda", "中野坂上", "Nakanosakaue", 29, 1, ["東京メトロ丸ノ内線", "都営地下鉄大江戸線",]],
    ["Kanda", "笹塚", "Sasazuka", 29, 1, ["京王線",]],
    ["Kanda", "新馬場", "Shinbanba", 29, 1, ["京急本線",]],
    ["Kanda", "都庁前", "Tochomae", 29, 1, ["都営地下鉄大江戸線",]],
    ["Kanda", "戸越公園", "Togoshikoen", 29, 1, ["東京急行電鉄東急大井町線",]],
    ["Kanda", "代々木八幡", "Yoyogihachiman", 29, 1, ["小田急電鉄小田原線",]],
    ["Kanda", "代々木上原", "Yoyogiuehara", 29, 1, ["東京メトロ千代田線", "小田急電鉄小田原線",]],
    ["Kanda", "国際展示場", "Kokusaitenjijo", 29, 2, ["りんかい線",]],
    ["Kanda", "市場前", "Market front", 29, 2, ["ゆりかもめ",]],
    ["Kanda", "西荻窪", "Nishiogikubo", 30, 0, ["JR中央線", "JR総武線",]],
    ["Kanda", "青物横丁", "Aomonoyokocho", 30, 1, ["京急本線",]],
    ["Kanda", "代田橋", "Daitabashi", 30, 1, ["京王線",]],
    ["Kanda", "向原", "Mukaihara", 30, 1, ["都電荒川線",]],
    ["Mitsukoshimae", "落合", "Ochiai", 30, 1, ["東京メトロ東西線",]],
    ["Kanda", "お台場海浜公園", "Odaibakaihinkoen", 30, 1, ["ゆりかもめ",]],
    ["Kanda", "巣鴨新田", "Sugamo Nitta", 30, 1, ["都電荒川線",]],
    ["Kanda", "戸越銀座", "Togoshi Ginza", 30, 1, ["東京急行電鉄東急池上線",]],
    ["Kanda", "牛田", "Ushita", 30, 1, ["東武伊勢崎線",]]
];

function processData() {
    let allLines = [];
    let allStations = [];
    for (entry of ALL_STATIONS) {
        for (line of entry[5]) {
            if (!allLines.includes(line)) {
                allLines.push(line);
            }
        }
        if (!allStations.includes(entry[1])) {
            allStations.push(entry[1]);
        }
    }

    return {
        coreData: ALL_STATIONS,
        allLines: allLines,
        allStations: allStations
    }
}

// Removed because the station is no good 
//     ["Mitsukoshimae", "浅草", "Asakusa", 15, 0, ["東京メトロ銀座線", "都営地下鉄浅草線", "東武伊勢崎線",]],
